#!/usr/bin/env python3
"""Validate approved WAV cues and embed their mono PCM samples in firmware."""
from hashlib import sha256
from pathlib import Path
import struct
import wave

ROOT = Path(__file__).resolve().parents[1]
AUDIO = ROOT / "assets" / "audio"
HEADER = ROOT / "firmware" / "Copilot" / "generated" / "audio_assets.h"
SOURCE = ROOT / "firmware" / "Copilot" / "src" / "audio_data.cpp"
SAMPLE_RATE = 24000
CUES = (
    ("Working", "working.wav"),
    ("Attention", "needs-attention.wav"),
    ("Complete", "complete.wav"),
    ("Surprise", "surprise.wav"),
    ("Settings", "settings-tick.wav"),
)


def samples(path):
    with wave.open(str(path), "rb") as wav:
        if (wav.getnchannels(), wav.getsampwidth(), wav.getframerate(), wav.getcomptype()) != (
                1, 2, SAMPLE_RATE, "NONE"):
            raise ValueError(f"{path} must be 24 kHz, 16-bit mono PCM")
        frames = wav.readframes(wav.getnframes())
        if wav.readframes(1):
            raise ValueError(f"{path} contains trailing audio frames")
    values = struct.unpack(f"<{len(frames) // 2}h", frames)
    if not values or max(abs(value) for value in values) > 32767:
        raise ValueError(f"{path} has invalid PCM samples")
    return values, sha256(path.read_bytes()).hexdigest()


def format_samples(values):
    lines = []
    for offset in range(0, len(values), 16):
        lines.append("  " + ", ".join(str(value) for value in values[offset:offset + 16]) + ",")
    return "\n".join(lines)


def main():
    loaded = [(name, *samples(AUDIO / filename)) for name, filename in CUES]
    declarations = "\n".join(
        f"extern const int16_t kAudio{name}[];\n"
        f"constexpr uint32_t kAudio{name}Samples = {len(values)};\n"
        f'constexpr const char* kAudio{name}Sha256 = "{digest}";'
        for name, values, digest in loaded
    )
    header = f"""// Generated by tools/embed_audio.py. Do not edit.
#pragma once
#include <cstdint>

namespace copilot {{
constexpr uint32_t kAudioPcmSampleRate = {SAMPLE_RATE};
{declarations}
}}
"""
    definitions = "\n\n".join(
        f"const int16_t kAudio{name}[] = {{\n{format_samples(values)}\n}};"
        for name, values, _ in loaded
    )
    source = f"""// Generated by tools/embed_audio.py. Do not edit.
#include "../generated/audio_assets.h"

namespace copilot {{
{definitions}
}}
"""
    HEADER.write_text(header)
    SOURCE.write_text(source)
    print(f"Embedded {sum(len(values) for _, values, _ in loaded):,} audio samples "
          f"({sum(len(values) for _, values, _ in loaded) * 2:,} PCM bytes)")


if __name__ == "__main__":
    main()
